# Generated by Django 3.2.9 on 2021-11-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='reg_no',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
